// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8dfUqhroMwN_XnpV342lqPJDaI42Cx6w',
    appId: '1:578003904265:web:c646409b11b3ce52b4d5d8',
    messagingSenderId: '578003904265',
    projectId: 'bubbleup-5ab0e',
    authDomain: 'bubbleup-5ab0e.firebaseapp.com',
    storageBucket: 'bubbleup-5ab0e.firebasestorage.app',
    measurementId: 'G-TPR4MQ96KT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJp7t8DH_RLQeryGFkxRaipopCeLDaon8',
    appId: '1:578003904265:android:85564542020dc699b4d5d8',
    messagingSenderId: '578003904265',
    projectId: 'bubbleup-5ab0e',
    storageBucket: 'bubbleup-5ab0e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9VtdwqYRD0GC8h2D30sKaRn70qxityXo',
    appId: '1:578003904265:ios:1cd2a4a7b2a4bd73b4d5d8',
    messagingSenderId: '578003904265',
    projectId: 'bubbleup-5ab0e',
    storageBucket: 'bubbleup-5ab0e.firebasestorage.app',
    iosBundleId: 'com.example.thammasat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9VtdwqYRD0GC8h2D30sKaRn70qxityXo',
    appId: '1:578003904265:ios:1cd2a4a7b2a4bd73b4d5d8',
    messagingSenderId: '578003904265',
    projectId: 'bubbleup-5ab0e',
    storageBucket: 'bubbleup-5ab0e.firebasestorage.app',
    iosBundleId: 'com.example.thammasat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8dfUqhroMwN_XnpV342lqPJDaI42Cx6w',
    appId: '1:578003904265:web:c4f5ab11b97e2ec4b4d5d8',
    messagingSenderId: '578003904265',
    projectId: 'bubbleup-5ab0e',
    authDomain: 'bubbleup-5ab0e.firebaseapp.com',
    storageBucket: 'bubbleup-5ab0e.firebasestorage.app',
    measurementId: 'G-WF2LYE3WVW',
  );
}
